### ISSUE TITLE
2.1 発射台---Launching Pad について議論する

### ISSUE THREAD

**Issue by Rindrics** [fra-dev-ops-bu/bookshelf#3]
ランチャについて議論しましょう。
（GitHubでの輪読は始めてなので、このIssueをどう閉じるかもまだ考えていません。適当なタイミングで本文にまとめようかと思います）

# キーワード
- ランチャー
- スタートメニュー
- Dock

**Comment by akikirinrin** [comment]
私は Macですが、OSレベルのランチャとして[Alfred](https://www.alfredapp.com)を使っています。

**Comment by akikirinrin** [comment]
## アプリ起動やシステムコントロール
<img width="668" alt="image" src="https://user-images.githubusercontent.com/14845847/84039385-219c1d80-a9dc-11ea-8eac-1f5ff82e64f4.png">

**Comment by akikirinrin** [comment]
# ファイル検索
pdf検索でよく使います
<img width="684" alt="image" src="https://user-images.githubusercontent.com/14845847/84039491-455f6380-a9dc-11ea-8178-6781ea041cc7.png">

**Comment by akikirinrin** [comment]
# Web検索
<img width="637" alt="image" src="https://user-images.githubusercontent.com/14845847/84039562-60ca6e80-a9dc-11ea-93ac-9b59e67675e1.png">

**Comment by akikirinrin** [comment]
# GitHubショートカット
<img width="633" alt="image" src="https://user-images.githubusercontent.com/14845847/84039639-80619700-a9dc-11ea-967b-ca53a4521046.png">

**Comment by akikirinrin** [comment]
# 自作ショートカット
<img width="766" alt="image" src="https://user-images.githubusercontent.com/14845847/84039847-ce769a80-a9dc-11ea-9668-1d474a476ccd.png">

**Comment by akikirinrin** [comment]
# 勤怠打刻
<img width="693" alt="image" src="https://user-images.githubusercontent.com/14845847/84039695-966f5780-a9dc-11ea-8f6a-be438beb5bc7.png">

**Comment by akikirinrin** [comment]
# Scrapbox
<img width="647" alt="image" src="https://user-images.githubusercontent.com/14845847/84039730-a6873700-a9dc-11ea-9509-57612fb7b1b2.png">

**Comment by akikirinrin** [comment]
# チートシート閲覧
<img width="621" alt="image" src="https://user-images.githubusercontent.com/14845847/84039891-df271080-a9dc-11ea-8689-644a0469af7f.png">

**Comment by akikirinrin** [comment]
# Dock

アプリは全てキーボードから起動するので、Dockはほぼ空っぽです

<img width="541" alt="image" src="https://user-images.githubusercontent.com/14845847/84040474-a63b6b80-a9dd-11ea-99d1-ef8c97c5365b.png">

**Comment by akikirinrin** [comment]
ファイル検索の2アクション選択です（あまり使いませんが）
<img width="580" alt="image" src="https://user-images.githubusercontent.com/14845847/84041354-b142cb80-a9de-11ea-9f09-366f5c66e4b1.png">

**Comment by JK-junkin** [comment]
Foooo!
わたしはデフォルトのspotlightです。

**Comment by Rindrics** [comment]
Alfred の workflows
https://github.com/willfarrell/alfred-workflows
