### ISSUE TITLE
第I部の内容について議論する

### ISSUE THREAD

**Issue by Rindrics** [fra-dev-ops-bu/bookshelf#36]
@akimanabe @JK-junkin 
ぼちぼちオフライン議論しましょう
# 議題
- [ ] 第I部のキモはなにか
- [ ] 書きぶりのすり合わせ
- [ ] 分量の調節
- [ ] ウェブページが見やすくなるようにファイルを分割

**Comment by akimanabe** [comment]
- 第I部 devopsとはなにか、のまとめを作成する。
- 各章へのリンクを作成する

**Comment by Rindrics** [comment]
オンラインレビュー、お疲れ様でした！！
