### ISSUE TITLE
4th Sprint

### ISSUE THREAD

**Issue by Rindrics** [fra-dev-ops-bu/bookshelf#63]

**Comment by Rindrics** [comment]
# レビュー
なし

**Comment by Rindrics** [comment]
認識しているproblemを列挙します
- ファイルを章ごとに分けないと読みにくくなってきている
- 「訪問者に理解されるかどうか」という観点から推敲する必要があるのではないか

**Comment by Rindrics** [comment]
# ふりかえり
@akimanabe @JK-junkin なにか問題があったらコメントお願いします:smile:

**Comment by akimanabe** [comment]
Chapterごとに情報量がだいぶ違いますね。

このmdを読んだらどうなるのか、どうあるべきか、で少し迷っています。

- １冊読んだのと同じ
- edoが読みたくなる
- まとめが理解できる
- devopsに必要なところが理解できる

など、何がまとめのGoalなのかというのを相談したいですね。

**Comment by Rindrics** [comment]
どれも、目指せたらいいね...
一番大事なのはこの本が伝えようとしていることをざっと理解できることかな？

**Comment by akimanabe** [comment]
この中から一つだけを選ばないといけない、というわけではありませんからね！:smiley:
